/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package base-4.4.0.0 */
#define VERSION_base "4.4.0.0"
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  4 || \
  (major1) == 4 && (major2) == 4 && (minor) <= 0)

