version: 0.1.6

ghc-options: -Wall

dependencies:
  - base >= 4.7
  - containers
  - uniplate
  - haskell-src-exts-simple

executables:
  typediff:
    main: Main.hs
    source-dirs:
      - driver
      - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
