name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-18.04 # https://launchpad.net/~hvr/+archive/ubuntu/ghc?field.series_filter=bionic
        ghc:
          - 7.0.4
          - 7.2.2
          - 7.4.2
          - 7.6.3
          - 7.8.4
          - 7.10.3
          - 8.0.2
          - 8.2.2
          - 8.4.4
          - 8.6.5
          - 8.8.4
          - 8.10.7
          - 9.0.2
          - 9.2.7
          - 9.4.4
          - 9.6.1
    steps:
      - uses: actions/checkout@v2
        # https://gitlab.haskell.org/ghc/ghc/-/issues/15444
      - name: Install libnuma-dev for ghc 8.4.4
        if: matrix.ghc == '8.4.4'
        run: sudo apt-get install libnuma-dev
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: install typediff
        run: |
          mkdir -p "$HOME/.local/bin"
          curl -L https://github.com/haskell-compat/base-compat/releases/download/typediff-0.1.5/typediff > "$HOME/.local/bin/typediff"
          chmod a+x "$HOME/.local/bin/typediff"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - run: cabal update
        # https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/123
      - name: Enable -optl-no-pie for ghc 7.10.3
        if: matrix.ghc == '7.10.3'
        run: |
          sed -i "s/-- ghc-options:.*/ghc-options: -optl-no-pie/" ~/.cabal/config

      - name: cabal configure
        run: |
          cabal configure --enable-tests ${{ env.enable_documentation }}
          echo -e "$EXTRAS" >> cabal.project.local
        env:
          EXTRAS: |
            package base-compat
              ghc-options: -Werror
            package base-compat-batteries
              ghc-options: -Werror
            package type-check
              ghc-options: -Werror

      - run: cabal build all
      - run: cabal test all --test-show-details=direct
        env:
          HSPEC_OPTIONS: --color
      - run: cabal haddock all
        # Old versions of Haddock have trouble building the documentation for
        # base-compat-batteries' Data.Type.Equality.Compat module:
        #
        # * GHC 7.2.2 runs into "synifyType: PredTys are not, in themselves, source-level types."
        #   This bug is apparently so obscure that no issue was ever filed about it!
        #
        # * GHC 7.6 runs into https://github.com/haskell/haddock/issues/242
        if: matrix.ghc != '7.2.2' && matrix.ghc != '7.6.3'

      - run: cd base-compat && cabal check
      - run: cd base-compat-batteries && cabal check

  success:
    needs: build
    runs-on: ubuntu-latest
    if: always() # this is required as GitHub considers "skipped" jobs as "passed" when checking branch protection rules

    steps:
      - run: false
        if: needs.build.result != 'success'
